package kz.kassayev.hibrain.initor;

import io.vertx.ext.sql.SQLOptions;
import io.vertx.rxjava.core.Vertx;
import io.vertx.rxjava.ext.jdbc.JDBCClient;
import rx.Completable;
import rx.Observable;

public class DBinit {

  private DBinit(){

  }

  public static Completable initDatabase(Vertx vertx, JDBCClient jdbcClient){
    return jdbcClient.rxGetConnection()
      .map(c -> c.setOptions(new SQLOptions().setAutoGeneratedKeys(true)))
      .flatMapCompletable(connection ->
        vertx.fileSystem().rxReadFile("ddl.sql")
          .flatMapObservable(buffer -> Observable.from(buffer.toString().split(";")))
          .flatMapSingle(connection::rxExecute)
          .doAfterTerminate(connection::close)
          .toCompletable()
      );
  }
}
